all:
  vars:
    ansible_user: user # Change me
    ansible_ssh_private_key_file: private-key-path # Change me
    ansible_python_interpreter: ../../.venv/bin/python

  children:
    servers:
      hosts:
        proxmox:
          ansible_host: 192.168.0.2
        dns:
          ansible_host: 192.168.0.10
    k8s-controllers:
      hosts:
        controller1:
          ansible_host: 192.168.0.20
    k8s-workers:
      hosts:
        worker1:
          ansible_host: 192.168.0.30
