---
- name: Retrieve K3s kubeconfig from remote VM
  hosts: controller1
  become: true
  tasks:

  - name: Read K3s kubeconfig file
    slurp:
      src: /etc/rancher/k3s/k3s.yaml
    register: k3s_config_raw

  - name: Write kubeconfig to local file
    copy:
      content: "{{ k3s_config_raw.content | b64decode }}"
      dest: "./k3s.yaml"
    delegate_to: localhost
    become: false # prevent Ansible from using sudo locally
