version: '3.8'

services:
  coredns:
    image: coredns/coredns:1.12.1
    container_name: coredns
    environment:
      - GOMAXPROCS=2
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "9153:9153/tcp"
    volumes:
      - ./Corefile:/Corefile
      - ./home.daniel-enrique.db:/zones/home.daniel-enrique.db
    command: -conf /Corefile
    restart: always